//
// Created by mt on 6/22/18.
//

#ifndef IMCODER_JUDGER_COMPILE_H
#define IMCODER_JUDGER_COMPILE_H

/**
 * the common config of compile
 * @var uid the user who execute the compile command
 * @var gid the group if of the user,maybe NULL */
struct compile_config {
    int uid;
    int gid;
};


/**
 * compile the target file
 * @param file the file will be compiled
 * @param output_file the file path of the execute file that generated by compile
 * @param compile_command the command use to compile file
 * @return the result of compile,if it work well, return 1,otherwise 0 */
int compile(char *file, char *output_file, char *compile_command, struct compile_config *config);


/**
 * this function will set the common filter to compile environment
 * @param ctx the filter context of compile environment */
void init_compile_seccomp_filter(scmp_filter_ctx *ctx);

#endif //IMCODER_JUDGER_COMPILE_H
